# Generated by Django 5.2.17 on 2026-10-05 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_bookmark_recurringtemplate_attachment_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('contact_person', models.CharField(blank=True, max_length=120, verbose_name='Contact person')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Phone')),
                ('tax_id', models.CharField(blank=True, max_length=30, verbose_name='Tax registration number')),
                ('commercial_register', models.CharField(blank=True, max_length=30, verbose_name='Commercial register')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='City')),
                ('country', models.CharField(blank=True, default='Egypt', max_length=80, verbose_name='Country')),
                ('payment_terms_days', models.PositiveIntegerField(default=30, verbose_name='Payment terms (days)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='0 means no limit.', max_digits=19, verbose_name='Credit limit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency')),
            ],
            options={
                'ordering': ['name_en'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uniq_customer_code')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('contact_person', models.CharField(blank=True, max_length=120, verbose_name='Contact person')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Phone')),
                ('tax_id', models.CharField(blank=True, max_length=30, verbose_name='Tax registration number')),
                ('commercial_register', models.CharField(blank=True, max_length=30, verbose_name='Commercial register')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='City')),
                ('country', models.CharField(blank=True, default='Egypt', max_length=80, verbose_name='Country')),
                ('payment_terms_days', models.PositiveIntegerField(default=30, verbose_name='Payment terms (days)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_details', models.TextField(blank=True, verbose_name='Bank details')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency')),
            ],
            options={
                'ordering': ['name_en'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uniq_supplier_code')],
            },
        ),
    ]
