# Generated by Django 5.2.17 on 2026-10-05 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.company'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency', verbose_name='Base currency'),
        ),
        migrations.AddField(
            model_name='company',
            name='currencies',
            field=models.ManyToManyField(blank=True, related_name='+', to='core.currency', verbose_name='Currencies in use'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.company'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='numberseries',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_branch_code'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('company', 'currency', 'date'), name='uniq_rate_per_day'),
        ),
        migrations.AddConstraint(
            model_name='numberseries',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='uniq_series_key'),
        ),
    ]
