# Generated by Django 5.2.17 on 2026-10-05 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('amount_fc', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=12, verbose_name='Type')),
                ('subtype', models.CharField(blank=True, choices=[('', 'General'), ('cash', 'Cash'), ('bank', 'Bank'), ('receivable', 'Customers (receivable)'), ('payable', 'Suppliers (payable)'), ('notes_receivable', 'Cheques in the safe (notes receivable)'), ('cheques_collection', 'Cheques under collection'), ('notes_payable', 'Cheques issued (notes payable)'), ('inventory', 'Inventory'), ('goods_in_transit', 'Goods in transit'), ('custody', 'Custody & advances'), ('vat_input', 'VAT input'), ('vat_output', 'VAT output'), ('wht_receivable', 'Withholding tax receivable'), ('wht_payable', 'Withholding tax payable'), ('retained_earnings', 'Retained earnings'), ('fx_gain', 'Exchange gains'), ('fx_loss', 'Exchange losses')], max_length=24, verbose_name='System role')),
                ('is_group', models.BooleanField(default=False, verbose_name='Header account (no postings)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_system', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency (foreign-currency accounts only)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ledger.account', verbose_name='Parent account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='core.company')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('date', models.DateField(db_index=True)),
                ('memo', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('manual', 'Manual journal'), ('receipt', 'Receipt voucher'), ('payment', 'Payment voucher'), ('journal', 'Journal voucher'), ('cheque', 'Cheque'), ('opening', 'Opening balance'), ('reversal', 'Reversal')], default='manual', max_length=12)),
                ('source_ref', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.company')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
