# Generated by Django 5.2.17 on 2026-10-05 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_bankrule_reconciliation_statementline'),
        ('contacts', '0001_initial'),
        ('core', '0003_bookmark_recurringtemplate_attachment_userpreference'),
        ('ledger', '0003_balance_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='banking.reconciliation'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subtype',
            field=models.CharField(blank=True, choices=[('', 'General'), ('cash', 'Cash'), ('bank', 'Bank'), ('receivable', 'Customers (receivable)'), ('payable', 'Suppliers (payable)'), ('notes_receivable', 'Cheques in the safe (notes receivable)'), ('cheques_collection', 'Cheques under collection'), ('notes_payable', 'Cheques issued (notes payable)'), ('inventory', 'Inventory'), ('goods_in_transit', 'Goods in transit'), ('custody', 'Custody & advances'), ('vat_input', 'VAT input'), ('vat_output', 'VAT output'), ('wht_receivable', 'Withholding tax receivable'), ('wht_payable', 'Withholding tax payable'), ('retained_earnings', 'Retained earnings'), ('fx_gain', 'Exchange gains'), ('fx_loss', 'Exchange losses'), ('grni', 'Goods received not invoiced'), ('sales', 'Sales revenue'), ('cogs', 'Cost of goods sold'), ('stock_adjustment', 'Stock adjustments'), ('price_variance', 'Purchase price variance'), ('fixed_assets', 'Fixed assets'), ('accum_depreciation', 'Accumulated depreciation'), ('depreciation', 'Depreciation expense'), ('disposal_gain', 'Gain on disposal'), ('disposal_loss', 'Loss on disposal'), ('salaries_payable', 'Salaries payable'), ('social_insurance', 'Social insurance payable'), ('payroll_tax', 'Salary tax payable'), ('employee_deductions', 'Employee deductions payable'), ('overtime', 'Overtime'), ('salaries', 'Salaries & wages'), ('employer_si', 'Employer social insurance'), ('opening_equity', 'Opening balance equity')], max_length=24, verbose_name='System role'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual journal'), ('receipt', 'Receipt voucher'), ('payment', 'Payment voucher'), ('journal', 'Journal voucher'), ('cheque', 'Cheque'), ('opening', 'Opening balance'), ('reversal', 'Reversal'), ('invoice', 'Sales invoice'), ('customer_payment', 'Customer payment'), ('bill', 'Supplier bill'), ('supplier_payment', 'Supplier payment'), ('receipt_goods', 'Item receipt'), ('stock', 'Stock adjustment'), ('depreciation', 'Depreciation'), ('asset', 'Asset disposal'), ('bank', 'Bank transaction'), ('payroll', 'Payroll')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On hold')], default='active', max_length=10, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Budget')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='contacts.customer', verbose_name='Customer')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='journalline',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.project'),
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Rate %')),
                ('kind', models.CharField(choices=[('standard', 'Standard rated'), ('zero', 'Zero rated'), ('exempt', 'Exempt'), ('out_of_scope', 'Out of scope')], default='standard', max_length=14, verbose_name='Type')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='core.company')),
            ],
            options={
                'ordering': ['-is_default', '-rate', 'name_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_project_code'),
        ),
    ]
