# Generated by Django 5.2.17 on 2026-10-05 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_bookmark_recurringtemplate_attachment_userpreference'),
        ('ledger', '0004_journalline_reconciliation_alter_account_subtype_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('provider', models.CharField(blank=True, max_length=160, verbose_name='Provider')),
                ('employer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Company share / month')),
                ('employee_cost', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Employee share / month')),
                ('coverage', models.CharField(blank=True, max_length=300, verbose_name='Coverage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_plans', to='core.company')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.company')),
                ('cost_center', models.ForeignKey(blank=True, help_text='Payroll costs of this department post here.', null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.costcenter', verbose_name='Cost centre')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.company')),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('code', models.CharField(help_text='Use the fingerprint ID so attendance imports match.', max_length=30, verbose_name='Employee code')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='National ID')),
                ('insurance_no', models.CharField(blank=True, max_length=30, verbose_name='Insurance number')),
                ('gender', models.CharField(blank=True, choices=[('', '—'), ('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='Gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Mobile')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Address')),
                ('job_title_en', models.CharField(blank=True, max_length=160, verbose_name='Job title (English)')),
                ('job_title_ar', models.CharField(blank=True, max_length=160, verbose_name='Job title (Arabic)')),
                ('spine_point', models.PositiveIntegerField(blank=True, null=True, verbose_name='Spine point')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Joining date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Leaving date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('hold', 'On hold'), ('left', 'Left')], default='active', max_length=6, verbose_name='Status')),
                ('contract_type', models.CharField(choices=[('indefinite', 'Indefinite'), ('fixed', 'Fixed term'), ('probation', 'Probation'), ('part_time', 'Part time'), ('contractor', 'Contractor')], default='indefinite', max_length=12, verbose_name='Contract')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Basic salary / month')),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Allowances / month')),
                ('insurable_wage', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use basic + allowances within the legal floor and ceiling.', max_digits=19, null=True, verbose_name='Insurable wage')),
                ('insured', models.BooleanField(default=True, verbose_name='Covered by social insurance')),
                ('taxable', models.BooleanField(default=True, verbose_name='Subject to salary tax')),
                ('payment_method', models.CharField(choices=[('bank', 'Bank transfer'), ('instapay', 'InstaPay'), ('cash', 'Cash')], default='bank', max_length=8, verbose_name='Paid by')),
                ('bank_name', models.CharField(blank=True, max_length=120, verbose_name='Bank')),
                ('bank_account', models.CharField(blank=True, max_length=60, verbose_name='Account / IBAN / InstaPay')),
                ('medical_employee_share', models.DecimalField(blank=True, decimal_places=2, help_text="Overrides the plan's employee share for this person.", max_digits=19, null=True, verbose_name='Medical deduction / month')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('benefit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='team.benefitplan', verbose_name='Medical plan')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='team.department', verbose_name='Department')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='team.grade', verbose_name='Grade')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual'), ('sick', 'Sick'), ('casual', 'Casual'), ('maternity', 'Maternity'), ('unpaid', 'Unpaid')], max_length=10, verbose_name='Type')),
                ('start_date', models.DateField(verbose_name='From')),
                ('end_date', models.DateField(verbose_name='To')),
                ('days', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Days')),
                ('paid_pct', models.DecimalField(decimal_places=2, default=100, max_digits=7, verbose_name='Paid %')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='team.employee', verbose_name='Employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('entitlement_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('accrued_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('taken_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('balance_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('provision_value', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='team.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Issue date')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount')),
                ('monthly_deduction', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Monthly deduction')),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Outstanding')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Reason')),
                ('status', models.CharField(choices=[('active', 'Active'), ('settled', 'Settled')], default='active', max_length=8, verbose_name='Status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='team.employee', verbose_name='Employee')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='team.loan')),
                ('payroll_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['pay_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpinePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_no', models.PositiveIntegerField(verbose_name='Spine point')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Monthly salary')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='team.grade')),
            ],
            options={
                'ordering': ['point_no'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Date')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Hours worked')),
                ('expected_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Expected hours')),
                ('ot_day_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('ot_night_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Night / rest-day overtime')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('holiday', 'Holiday')], default='present', max_length=8, verbose_name='Status')),
                ('source', models.CharField(default='import', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='team.employee')),
            ],
            options={
                'ordering': ['-work_date', 'employee__code'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date'), name='uniq_attendance_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_employee_code'),
        ),
        migrations.AddConstraint(
            model_name='leaveprovision',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'month', 'employee'), name='uniq_leave_provision'),
        ),
    ]
