# Generated by Django 5.2.17 on 2026-10-05 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('core', '0003_bookmark_recurringtemplate_attachment_userpreference'),
        ('ledger', '0003_balance_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('useful_life_months', models.PositiveIntegerField(default=60, verbose_name='Useful life (months)')),
            ],
            options={
                'verbose_name_plural': 'asset categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='AssetCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('open', 'Counting'), ('closed', 'Closed')], default='open', max_length=6, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=120, verbose_name='Condition')),
            ],
            options={
                'ordering': ['asset__number'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='DepreciationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Month')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Asset number')),
                ('serial_no', models.CharField(blank=True, max_length=80, verbose_name='Serial number')),
                ('purchase_date', models.DateField(verbose_name='Purchase date')),
                ('in_service_date', models.DateField(verbose_name='Depreciation starts')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Cost')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Residual value')),
                ('useful_life_months', models.PositiveIntegerField(verbose_name='Useful life (months)')),
                ('opening_depreciation', models.DecimalField(decimal_places=2, default=0, help_text='For assets bought before you started using TriB.', max_digits=19, verbose_name='Depreciation before TriB')),
                ('location_detail', models.CharField(blank=True, max_length=120, verbose_name='Room / area')),
                ('custodian', models.CharField(blank=True, max_length=120, verbose_name='Custodian')),
                ('status', models.CharField(choices=[('active', 'In use'), ('idle', 'Not in use'), ('disposed', 'Disposed'), ('missing', 'Missing')], default='active', max_length=10, verbose_name='Status')),
                ('disposed_on', models.DateField(blank=True, null=True, verbose_name='Disposal date')),
                ('disposal_proceeds', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Sale proceeds')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.company')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.costcenter', verbose_name='Cost centre')),
                ('disposal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.supplier', verbose_name='Supplier')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
