# Generated by Django 5.2.17 on 2026-10-05 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0003_bookmark_recurringtemplate_attachment_userpreference'),
        ('inventory', '0001_initial'),
        ('ledger', '0004_journalline_reconciliation_alter_account_subtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='asset_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account', verbose_name='Asset account'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='core.company'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='depreciation_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account', verbose_name='Accumulated depreciation account'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='expense_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account', verbose_name='Depreciation expense account'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.assetcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='assetcount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='assetcount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='assetcount',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcount',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='assetcountline',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetcountline',
            name='count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='assets.assetcount'),
        ),
        migrations.AddField(
            model_name='depreciationline',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_lines', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='depreciationrun',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='depreciationrun',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depreciationrun',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry'),
        ),
        migrations.AddField(
            model_name='depreciationline',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='assets.depreciationrun'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uniq_asset_number'),
        ),
        migrations.AddConstraint(
            model_name='depreciationrun',
            constraint=models.UniqueConstraint(fields=('company', 'period'), name='uniq_depreciation_month'),
        ),
    ]
