"""Reference currencies (ISO 4217). Companies activate the ones they use."""

# code, English name, Arabic name, minor-unit decimals, Arabic short symbol
CURRENCIES = [
    ("EGP", "Egyptian pound", "جنيه مصري", 2, "ج.م"),
    ("USD", "US dollar", "دولار أمريكي", 2, "دولار"),
    ("EUR", "Euro", "يورو", 2, "يورو"),
    ("GBP", "Pound sterling", "جنيه إسترليني", 2, "إسترليني"),
    ("SAR", "Saudi riyal", "ريال سعودي", 2, "ر.س"),
    ("AED", "UAE dirham", "درهم إماراتي", 2, "د.إ"),
    ("KWD", "Kuwaiti dinar", "دينار كويتي", 3, "د.ك"),
    ("QAR", "Qatari riyal", "ريال قطري", 2, "ر.ق"),
    ("BHD", "Bahraini dinar", "دينار بحريني", 3, "د.ب"),
    ("OMR", "Omani rial", "ريال عماني", 3, "ر.ع"),
    ("JOD", "Jordanian dinar", "دينار أردني", 3, "د.أ"),
    ("LBP", "Lebanese pound", "ليرة لبنانية", 2, "ل.ل"),
    ("IQD", "Iraqi dinar", "دينار عراقي", 3, "د.ع"),
    ("LYD", "Libyan dinar", "دينار ليبي", 3, "د.ل"),
    ("TND", "Tunisian dinar", "دينار تونسي", 3, "د.ت"),
    ("DZD", "Algerian dinar", "دينار جزائري", 2, "د.ج"),
    ("MAD", "Moroccan dirham", "درهم مغربي", 2, "د.م"),
    ("SDG", "Sudanese pound", "جنيه سوداني", 2, "ج.س"),
    ("YER", "Yemeni rial", "ريال يمني", 2, "ر.ي"),
    ("SYP", "Syrian pound", "ليرة سورية", 2, "ل.س"),
    ("CNY", "Chinese yuan", "يوان صيني", 2, "يوان"),
    ("JPY", "Japanese yen", "ين ياباني", 0, "ين"),
    ("INR", "Indian rupee", "روبية هندية", 2, "روبية"),
    ("TRY", "Turkish lira", "ليرة تركية", 2, "ليرة"),
    ("CHF", "Swiss franc", "فرنك سويسري", 2, "فرنك"),
    ("CAD", "Canadian dollar", "دولار كندي", 2, "دولار كندي"),
    ("AUD", "Australian dollar", "دولار أسترالي", 2, "دولار أسترالي"),
    ("SEK", "Swedish krona", "كرونة سويدية", 2, "كرونة"),
    ("NOK", "Norwegian krone", "كرونة نرويجية", 2, "كرونة"),
    ("DKK", "Danish krone", "كرونة دنماركية", 2, "كرونة"),
    ("RUB", "Russian rouble", "روبل روسي", 2, "روبل"),
    ("ZAR", "South African rand", "راند جنوب أفريقي", 2, "راند"),
    ("KRW", "South Korean won", "وون كوري", 0, "وون"),
    ("SGD", "Singapore dollar", "دولار سنغافوري", 2, "دولار سنغافوري"),
    ("HKD", "Hong Kong dollar", "دولار هونغ كونغ", 2, "دولار هونغ كونغ"),
    ("MYR", "Malaysian ringgit", "رينغيت ماليزي", 2, "رينغيت"),
    ("IDR", "Indonesian rupiah", "روبية إندونيسية", 2, "روبية"),
    ("PKR", "Pakistani rupee", "روبية باكستانية", 2, "روبية"),
    ("BDT", "Bangladeshi taka", "تاكا بنغلاديشية", 2, "تاكا"),
    ("NGN", "Nigerian naira", "نايرا نيجيرية", 2, "نايرا"),
    ("KES", "Kenyan shilling", "شلن كيني", 2, "شلن"),
    ("ETB", "Ethiopian birr", "بير إثيوبي", 2, "بير"),
    ("BRL", "Brazilian real", "ريال برازيلي", 2, "ريال برازيلي"),
    ("MXN", "Mexican peso", "بيزو مكسيكي", 2, "بيزو"),
]

# Spoken names of each currency's main and minor unit, used for amounts in words.
# code: (English unit plural, English minor plural, Arabic unit, Arabic minor)
CURRENCY_WORDS = {
    "EGP": ("Egyptian pounds", "piastres", "جنيه مصري", "قرش"),
    "USD": ("US dollars", "cents", "دولار أمريكي", "سنت"),
    "EUR": ("euros", "cents", "يورو", "سنت"),
    "GBP": ("pounds sterling", "pence", "جنيه إسترليني", "بنس"),
    "SAR": ("Saudi riyals", "halalas", "ريال سعودي", "هللة"),
    "AED": ("UAE dirhams", "fils", "درهم إماراتي", "فلس"),
    "KWD": ("Kuwaiti dinars", "fils", "دينار كويتي", "فلس"),
    "QAR": ("Qatari riyals", "dirhams", "ريال قطري", "درهم"),
    "BHD": ("Bahraini dinars", "fils", "دينار بحريني", "فلس"),
    "OMR": ("Omani rials", "baisa", "ريال عماني", "بيسة"),
    "JOD": ("Jordanian dinars", "fils", "دينار أردني", "فلس"),
    "CNY": ("Chinese yuan", "fen", "يوان صيني", "فين"),
}
