"""Banks offered in the bank list. Companies can add any bank that is missing.

SWIFT/BIC codes are left for each company to enter from its own bank letters, so that no
payment instruction ever relies on a code we typed in.
"""

# country, short name, English name, Arabic name
BANKS = [
    ("EG", "NBE", "National Bank of Egypt", "البنك الأهلي المصري"),
    ("EG", "BM", "Banque Misr", "بنك مصر"),
    ("EG", "CIB", "Commercial International Bank (CIB)", "البنك التجاري الدولي"),
    ("EG", "BDC", "Banque du Caire", "بنك القاهرة"),
    ("EG", "QNB", "QNB Egypt", "بنك قطر الوطني مصر"),
    ("EG", "AAIB", "Arab African International Bank", "البنك العربي الأفريقي الدولي"),
    ("EG", "HSBC", "HSBC Bank Egypt", "بنك إتش إس بي سي مصر"),
    ("EG", "ALEX", "Bank of Alexandria", "بنك الإسكندرية"),
    ("EG", "CAE", "Crédit Agricole Egypt", "بنك كريدي أجريكول مصر"),
    ("EG", "FAIB", "Faisal Islamic Bank of Egypt", "بنك فيصل الإسلامي المصري"),
    ("EG", "ADIB", "Abu Dhabi Islamic Bank Egypt", "مصرف أبوظبي الإسلامي مصر"),
    ("EG", "ENBD", "Emirates NBD Egypt", "بنك الإمارات دبي الوطني مصر"),
    ("EG", "FAB", "FABMISR (First Abu Dhabi Bank Misr)", "بنك أبوظبي الأول مصر"),
    ("EG", "ADCB", "Abu Dhabi Commercial Bank Egypt", "بنك أبوظبي التجاري مصر"),
    ("EG", "MASH", "Mashreq Bank Egypt", "بنك المشرق مصر"),
    ("EG", "NBK", "National Bank of Kuwait Egypt", "بنك الكويت الوطني مصر"),
    ("EG", "KFH", "Kuwait Finance House Egypt", "بيت التمويل الكويتي مصر"),
    ("EG", "ABK", "Al Ahli Bank of Kuwait Egypt", "البنك الأهلي الكويتي مصر"),
    ("EG", "BARAKA", "Al Baraka Bank Egypt", "بنك البركة مصر"),
    ("EG", "SAIB", "SAIB Bank", "بنك الشركة المصرفية العربية الدولية"),
    ("EG", "HDB", "Housing and Development Bank", "بنك التعمير والإسكان"),
    ("EG", "SCB", "Suez Canal Bank", "بنك قناة السويس"),
    ("EG", "EGB", "Egyptian Gulf Bank", "البنك المصري الخليجي"),
    ("EG", "AWB", "Attijariwafa Bank Egypt", "التجاري وفا بنك مصر"),
    ("EG", "ARAB", "Arab Bank Egypt", "البنك العربي مصر"),
    ("EG", "AIB", "Arab International Bank", "المصرف العربي الدولي"),
    ("EG", "ABE", "Agricultural Bank of Egypt", "البنك الزراعي المصري"),
    ("EG", "EDBE", "Export Development Bank of Egypt", "البنك المصري لتنمية الصادرات"),
    ("EG", "IDB", "Industrial Development Bank", "بنك التنمية الصناعية"),
    ("EG", "CITI", "Citibank Egypt", "سيتي بنك مصر"),
    ("AE", "FAB", "First Abu Dhabi Bank", "بنك أبوظبي الأول"),
    ("AE", "ENBD", "Emirates NBD", "بنك الإمارات دبي الوطني"),
    ("AE", "ADCB", "Abu Dhabi Commercial Bank", "بنك أبوظبي التجاري"),
    ("AE", "ADIB", "Abu Dhabi Islamic Bank", "مصرف أبوظبي الإسلامي"),
    ("AE", "DIB", "Dubai Islamic Bank", "بنك دبي الإسلامي"),
    ("AE", "MASH", "Mashreq", "بنك المشرق"),
    ("AE", "CBD", "Commercial Bank of Dubai", "بنك دبي التجاري"),
    ("AE", "RAK", "RAKBANK", "بنك رأس الخيمة الوطني"),
    ("SA", "SNB", "Saudi National Bank", "البنك الأهلي السعودي"),
    ("SA", "RAJHI", "Al Rajhi Bank", "مصرف الراجحي"),
    ("SA", "RIYAD", "Riyad Bank", "بنك الرياض"),
    ("SA", "SAB", "Saudi Awwal Bank", "البنك السعودي الأول"),
    ("SA", "BSF", "Banque Saudi Fransi", "البنك السعودي الفرنسي"),
    ("SA", "ALINMA", "Alinma Bank", "مصرف الإنماء"),
    ("SA", "ANB", "Arab National Bank", "البنك العربي الوطني"),
    ("KW", "NBK", "National Bank of Kuwait", "بنك الكويت الوطني"),
    ("KW", "KFH", "Kuwait Finance House", "بيت التمويل الكويتي"),
    ("QA", "QNB", "Qatar National Bank", "بنك قطر الوطني"),
    ("BH", "NBB", "National Bank of Bahrain", "بنك البحرين الوطني"),
    ("OM", "BM", "Bank Muscat", "بنك مسقط"),
    ("JO", "ARAB", "Arab Bank", "البنك العربي"),
    ("GB", "HSBC", "HSBC UK", "إتش إس بي سي المملكة المتحدة"),
    ("GB", "BARC", "Barclays", "باركليز"),
]
