# Generated by Django 5.2.17 on 2026-10-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('short_name', models.CharField(max_length=20, verbose_name='Short name')),
                ('country', models.CharField(choices=[('EG', 'Egypt'), ('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('KW', 'Kuwait'), ('QA', 'Qatar'), ('BH', 'Bahrain'), ('OM', 'Oman'), ('JO', 'Jordan'), ('GB', 'United Kingdom'), ('XX', 'Other')], default='EG', max_length=2, verbose_name='Country')),
                ('swift', models.CharField(blank=True, max_length=11, verbose_name='SWIFT / BIC')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['country', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('kind', models.CharField(choices=[('bank', 'Bank account'), ('cash', 'Cash box')], default='bank', max_length=4, verbose_name='Type')),
                ('account_number', models.CharField(blank=True, max_length=40, verbose_name='Account number')),
                ('iban', models.CharField(blank=True, max_length=40, verbose_name='IBAN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['kind', 'gl_account__code'],
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Received'), ('out', 'Issued')], max_length=3, verbose_name='Direction')),
                ('number', models.CharField(max_length=40, verbose_name='Cheque number')),
                ('drawee_bank', models.CharField(blank=True, max_length=120, verbose_name='Drawn on bank')),
                ('party_name', models.CharField(max_length=200, verbose_name='Customer / supplier')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount')),
                ('rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('issue_date', models.DateField(verbose_name='Cheque date')),
                ('due_date', models.DateField(db_index=True, verbose_name='Due date')),
                ('status', models.CharField(choices=[('in_safe', 'In the safe'), ('under_collection', 'Under collection'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status')),
                ('source_ref', models.CharField(blank=True, max_length=40)),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
    ]
