# Generated by Django 5.2.17 on 2026-10-05 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0002_initial'),
        ('core', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='gl_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='banking.bankaccount', verbose_name='Our bank account'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='core.company'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='counter_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account'),
        ),
    ]
