# Generated by Django 5.2.17 on 2026-10-05 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_initial'),
        ('core', '0003_bookmark_recurringtemplate_attachment_userpreference'),
        ('ledger', '0003_balance_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Rule name')),
                ('contains', models.CharField(max_length=120, verbose_name='Description contains')),
                ('direction', models.CharField(choices=[('any', 'Money in or out'), ('in', 'Money in'), ('out', 'Money out')], default='any', max_length=3, verbose_name='Applies to')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='Memo')),
                ('auto_post', models.BooleanField(default=False, verbose_name='Post automatically when imported')),
                ('priority', models.PositiveSmallIntegerField(default=10, verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account', verbose_name='Categorise as')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_rules', to='core.company')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(verbose_name='Statement end date')),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Statement ending balance')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('open', 'In progress'), ('done', 'Reconciled')], default='open', max_length=4, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='banking.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-statement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Reference')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount')),
                ('status', models.CharField(choices=[('new', 'For review'), ('matched', 'Matched'), ('posted', 'Categorised'), ('excluded', 'Excluded')], db_index=True, default='new', max_length=8, verbose_name='Status')),
                ('import_batch', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_lines', to='banking.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('journal_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.journalline')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='banking.bankrule')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
