# Generated by Django 5.2.17 on 2026-10-08 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_bankrule_reconciliation_statementline'),
        ('contacts', '0001_initial'),
        ('core', '0003_bookmark_recurringtemplate_attachment_userpreference'),
        ('ledger', '0005_release2_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='bounce_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Times returned'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='bounce_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Reason returned'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='bounced_on',
            field=models.DateField(blank=True, null=True, verbose_name='Bounced on'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='cleared_on',
            field=models.DateField(blank=True, null=True, verbose_name='Cleared on'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='contacts.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.CharField(choices=[('in_safe', 'In the safe'), ('under_collection', 'Under collection'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('issued', 'Issued'), ('cancelled', 'Cancelled'), ('settled', 'Settled by cash or transfer')], max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ChequeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('deposited', 'Deposited for collection'), ('cleared', 'Cleared'), ('bounced', 'Returned unpaid'), ('resubmitted', 'Resubmitted to the bank'), ('settled', 'Settled by cash or transfer'), ('cancelled', 'Cancelled')], max_length=12, verbose_name='Action')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Reference')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='banking.bankaccount')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='banking.cheque')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('statement_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='banking.statementline')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
