# Generated by Django 5.2.17 on 2026-10-05 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_bookmark_recurringtemplate_attachment_userpreference'),
        ('ledger', '0004_journalline_reconciliation_alter_account_subtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('prefix', models.CharField(help_text='Used to build SKUs, e.g. MCH → MCH-00001', max_length=6, verbose_name='SKU prefix')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('sku', models.CharField(blank=True, help_text='Leave empty to number it automatically.', max_length=40, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, help_text='Manufacturer barcode if it has one; otherwise the SKU is used.', max_length=60, verbose_name='Barcode')),
                ('type', models.CharField(choices=[('inventory', 'Stock item'), ('non_inventory', 'Non-stock item'), ('service', 'Service')], default='inventory', max_length=14, verbose_name='Type')),
                ('tracking', models.CharField(choices=[('none', 'No tracking'), ('serial', 'Serial numbers'), ('batch', 'Batch & expiry date')], default='none', max_length=6, verbose_name='Tracking')),
                ('unit', models.CharField(default='pcs', max_length=20, verbose_name='Unit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sales_price', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Sales price')),
                ('purchase_cost', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Purchase cost')),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=19, verbose_name='Reorder level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.company')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account', verbose_name='Cost / expense account')),
                ('income_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account', verbose_name='Income account')),
                ('inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.account', verbose_name='Inventory account')),
                ('purchase_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.taxrate', verbose_name='Purchase VAT')),
                ('sales_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.taxrate', verbose_name='Sales VAT')),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10, verbose_name='Status')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('count', 'Stock take difference'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('lost', 'Lost or stolen'), ('found', 'Found'), ('opening', 'Opening stock'), ('other', 'Other')], default='other', max_length=10, verbose_name='Reason')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_change', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='Quantity + / −')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Unit cost (for increases)')),
                ('serials', models.TextField(blank=True, verbose_name='Serial numbers')),
                ('batch_no', models.CharField(blank=True, max_length=60, verbose_name='Batch')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry date')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10, verbose_name='Status')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjustment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stockadjustment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.DecimalField(decimal_places=3, max_digits=19)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
            ],
            options={
                'ordering': ['item__sku'],
            },
        ),
        migrations.CreateModel(
            name='StockLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ref', models.CharField(blank=True, max_length=40)),
                ('qty_in', models.DecimalField(decimal_places=3, max_digits=19)),
                ('qty_remaining', models.DecimalField(decimal_places=3, max_digits=19)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('serial_no', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Serial number')),
                ('batch_no', models.CharField(blank=True, max_length=60, verbose_name='Batch')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layers', to='inventory.item')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10, verbose_name='Status')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=19, verbose_name='Quantity')),
                ('serials', models.TextField(blank=True, help_text='One per line, for serial-tracked items.', verbose_name='Serial numbers')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='Item')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktransfer')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.company')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse', verbose_name='From'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse', verbose_name='To'),
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('adjust_in', 'Adjustment in'), ('adjust_out', 'Adjustment out'), ('opening', 'Opening stock'), ('return', 'Return')], max_length=14)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=19)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ref', models.CharField(blank=True, max_length=40)),
                ('serial_no', models.CharField(blank=True, max_length=80)),
                ('batch_no', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='inventory.item')),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='inventory.stocklayer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='stocklayer',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layers', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company', 'prefix'), name='uniq_category_prefix'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('company', 'sku'), name='uniq_item_sku'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_warehouse_code'),
        ),
        migrations.AddIndex(
            model_name='stocklayer',
            index=models.Index(fields=['item', 'warehouse', 'qty_remaining'], name='inventory_s_item_id_841439_idx'),
        ),
    ]
