# Generated by Django 5.2.17 on 2026-10-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_main_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
