# Generated by Django 5.2.17 on 2026-10-05 17:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0005_bankrule_reconciliation_statementline'),
        ('core', '0003_bookmark_recurringtemplate_attachment_userpreference'),
        ('ledger', '0004_journalline_reconciliation_alter_account_subtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('insurable_wage', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('si_employee', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('si_employer', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('emergency_fund', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('employer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('hours_expected', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('comment', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['employee__code'],
            },
        ),
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('si', 'Social insurance (NOSI)'), ('tax', 'Salary tax'), ('medical', 'Medical & other deductions')], max_length=8)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('reference', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='DelegationBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Band')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='From net total')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Up to net total')),
                ('requires_fm', models.BooleanField(default=True, verbose_name='Finance Manager approval')),
                ('requires_md', models.BooleanField(default=True, verbose_name='Managing Director authorisation')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
            ],
            options={
                'ordering': ['order', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Month')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('prepared', 'Waiting for Finance Manager'), ('approved', 'Waiting for Managing Director'), ('authorised', 'Authorised'), ('paid', 'Paid')], default='draft', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('authorised_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=300)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='core.company')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_no', models.CharField(blank=True, max_length=60, verbose_name='Employer insurance number')),
                ('standard_daily_hours', models.DecimalField(decimal_places=2, default=8, max_digits=6, verbose_name='Standard hours per day')),
                ('standard_weekly_hours', models.DecimalField(decimal_places=2, default=48, max_digits=6, verbose_name='Standard hours per week')),
                ('working_days', models.CharField(default='SU,MO,TU,WE,TH', max_length=40, verbose_name='Working days')),
                ('days_per_month', models.PositiveSmallIntegerField(default=30, verbose_name='Days per month (for daily rate)')),
                ('si_employee_pct', models.DecimalField(decimal_places=2, default=Decimal('11.00'), max_digits=6, verbose_name='Social insurance — employee %')),
                ('si_employer_pct', models.DecimalField(decimal_places=2, default=Decimal('18.75'), max_digits=6, verbose_name='Social insurance — employer %')),
                ('emergency_fund_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='Emergency fund — employer %')),
                ('si_floor', models.DecimalField(decimal_places=2, default=Decimal('2700'), max_digits=19, verbose_name='Insurable wage floor / month')),
                ('si_ceiling', models.DecimalField(decimal_places=2, default=Decimal('16700'), max_digits=19, verbose_name='Insurable wage ceiling / month')),
                ('tax_annual_exemption', models.DecimalField(decimal_places=2, default=Decimal('20000'), max_digits=19, verbose_name='Annual salary tax exemption')),
                ('overtime_day_pct', models.DecimalField(decimal_places=2, default=Decimal('35'), max_digits=6, verbose_name='Overtime premium — day %')),
                ('overtime_night_pct', models.DecimalField(decimal_places=2, default=Decimal('70'), max_digits=6, verbose_name='Overtime premium — night / rest day %')),
                ('annual_leave_y1', models.PositiveSmallIntegerField(default=15, verbose_name='Annual leave — first year (days)')),
                ('annual_leave_std', models.PositiveSmallIntegerField(default=21, verbose_name='Annual leave — standard (days)')),
                ('annual_leave_senior', models.PositiveSmallIntegerField(default=30, verbose_name='Annual leave — senior (days)')),
                ('casual_leave', models.PositiveSmallIntegerField(default=7, verbose_name='Casual leave (days)')),
                ('probation_months', models.PositiveSmallIntegerField(default=3, verbose_name='Probation (months)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_settings', to='core.company')),
                ('pay_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='banking.bankaccount', verbose_name='Salaries paid from')),
                ('pay_cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='banking.bankaccount', verbose_name='Cash salaries paid from')),
            ],
        ),
    ]
