# Generated by Django 5.2.17 on 2026-10-05 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0005_bankrule_reconciliation_statementline'),
        ('ledger', '0004_journalline_reconciliation_alter_account_subtype_and_more'),
        ('payroll', '0001_initial'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='team.employee'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remittance',
            name='journal_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='payroll.payrollrun'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'month'), name='uniq_payroll_period'),
        ),
        migrations.AddConstraint(
            model_name='remittance',
            constraint=models.UniqueConstraint(fields=('run', 'kind'), name='uniq_remittance_kind'),
        ),
    ]
