# Generated by Django 5.2.17 on 2026-10-05 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0003_initial'),
        ('core', '0001_initial'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Receipt voucher'), ('payment', 'Payment voucher'), ('journal', 'Journal voucher')], max_length=10)),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Waiting for approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=10, verbose_name='Status')),
                ('party_name', models.CharField(blank=True, max_length=200, verbose_name='Received from / paid to')),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('cheque', 'Cheque')], max_length=6, verbose_name='Payment method')),
                ('rate', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='Exchange rate')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('cheque_number', models.CharField(blank=True, max_length=40, verbose_name='Cheque number')),
                ('cheque_bank', models.CharField(blank=True, max_length=120, verbose_name='Drawn on bank')),
                ('cheque_due_date', models.DateField(blank=True, null=True, verbose_name='Cheque due date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='banking.bankaccount', verbose_name='Cash box / bank account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch')),
                ('cheque', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher', to='banking.cheque')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher', to='ledger.journalentry')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Amount')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Credit')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.account', verbose_name='Account')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.costcenter', verbose_name='Cost centre')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vouchers.voucher')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
