# Generated by Django 5.2.17 on 2026-10-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('decision', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected')], max_length=10)),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Comment')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_at', models.DateTimeField()),
                ('signature', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['order', 'signed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_order', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('amount_base', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('receipt', 'Receipt voucher'), ('payment', 'Payment voucher'), ('journal', 'Journal voucher')], max_length=20, verbose_name='Document type')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='From amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['doc_type', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Level')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
