# Generated by Django 5.2.17 on 2026-10-05 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='vouchers.voucher'),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalrequest'),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='core.company'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approvals.approvalrule'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.role', verbose_name='Approver role'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalrule'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('rule', 'order'), name='uniq_step_order'),
        ),
    ]
