# Generated by Django 5.2.17 on 2026-10-05 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0005_bankrule_reconciliation_statementline'),
        ('contacts', '0001_initial'),
        ('core', '0003_bookmark_recurringtemplate_attachment_userpreference'),
        ('inventory', '0001_initial'),
        ('ledger', '0004_journalline_reconciliation_alter_account_subtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Payment date')),
                ('rate', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='Exchange rate')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount received')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('cheque', 'Cheque')], default='bank', max_length=6, verbose_name='Payment method')),
                ('cheque_number', models.CharField(blank=True, max_length=40, verbose_name='Cheque number')),
                ('cheque_bank', models.CharField(blank=True, max_length=120, verbose_name='Drawn on bank')),
                ('cheque_due_date', models.DateField(blank=True, null=True, verbose_name='Cheque due date')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='Reference')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Notes')),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=6, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='banking.bankaccount', verbose_name='Deposit to')),
                ('cheque', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='banking.cheque')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contacts.customer', verbose_name='Customer')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('rate', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='Exchange rate')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', max_length=10, verbose_name='Status')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='contacts.customer', verbose_name='Customer')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.journalentry')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='Ship from warehouse')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sales.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.customerpayment')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('rate', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='Exchange rate')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid until')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('converted', 'Converted')], default='draft', max_length=10, verbose_name='Status')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='contacts.customer', verbose_name='Customer')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=19, verbose_name='Qty')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Rate')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Disc. %')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.account', verbose_name='Account')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.quotation')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='Product / service')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.project', verbose_name='Project')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.taxrate', verbose_name='VAT')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('rate', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='Exchange rate')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Delivery date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('partial', 'Partly invoiced'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='draft', max_length=10, verbose_name='Status')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='Branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='contacts.customer', verbose_name='Customer')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.quotation')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.salesorder'),
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=19, verbose_name='Qty')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Rate')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Disc. %')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.account', verbose_name='Account')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='Product / service')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.project', verbose_name='Project')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.taxrate', verbose_name='VAT')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=19, verbose_name='Qty')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Rate')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Disc. %')),
                ('serials', models.TextField(blank=True, help_text='Optional: which machines are sold.', verbose_name='Serial numbers')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.account', verbose_name='Account')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.invoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='Product / service')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.project', verbose_name='Project')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.taxrate', verbose_name='VAT')),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='sales.salesorderline')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
